## Programming Assignment 8

### 1.	Write a Python Program to Add Two Matrices?

In [22]:
a1 = [[1,2,3],
      [4,5,6],
      [7,8,9]]

a2 = [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]
print(f'Inout: \n {a1}; {a2}')

Inout: 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]; [[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [7]:
# method 1
if len(a1) == len(a2):
    out_matrix = []
    for ele in range(len(a1)):
        if len(a1[ele]) == len(a2[ele]):
            out_matrix.append([])
            for s_ele in range(len(a1[ele])):
                out_matrix[ele].append(a1[ele][s_ele]+ a2[ele][s_ele])
        else:
            print('Both Matrices must contains same no of rows and columns') 
else:
    print('Both Matrices must contains same no of rows and columns')
print(f'Output: {out_matrix}')

Output: [[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [9]:
# Method 2
import numpy as np

msum = np.add(a1, a2)
print(f"Output: \n {msum}")

Output: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


### Q2. Write a Python Program to Multiply Two Matrices?

In [12]:
# method 1
def multiply_matrice(a,b):
    output = []
    if len(a[0]) == len(b):
        for ele in range(len(a[0])):
            output.append([0 for ele in range(len(b[0]))])
        for i in range(len(a)):
            for j in range(len(b[0])):
                for k in range(len(b)):
                    output[i][j] += a[i][k]*b[k][j]
        print(output)     
    else:
        print('Matrix Multiplication is Not Possible')
        
multiply_matrice(a1,a2)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


In [13]:
mulMat = np.dot(a1,a2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(a1,a2,mulMat))

The product of two matrix 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]  and 

[[9, 8, 7], [6, 5, 4], [3, 2, 1]]  is 

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]] 


### Q3. Write a Python Program to Transpose a Matrix?

In [33]:
out_mat = []
for ele in range(len(a1[0])):
    out_mat.append([0 for i in range(len(a1))])
for i in range(len(a1)):
    for j in range(len(a1[i])):
        out_mat[j][i] = a1[i][j]
print('Input:')
for i in a1:
    print(i)
print('\n Output:')
for i in out_mat:
    print(i)

Input:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

 Output:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


### Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [39]:
#Method 1

s = input("Enter a string: ")

w = s.split()
w.sort()
for i in w:
    print(i)

Enter a string: my name is neetu rani paul
is
my
name
neetu
paul
rani


In [41]:
# Method 2

def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString()

Enter a String: My name is neetu rani paul
Is My Name Neetu Paul Rani


### Q5. Write a Python Program to remove Punctuations From a String ?

In [42]:
def remove_punctuation():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    s = input("Enter a string: ")
    inp = ''
    for i in s:
        if i not in punctuations:
            inp += i
            
    print(f'Output: {inp}')

In [43]:
remove_punctuation()

Enter a string: My name is, neetu. but ??? what !! is this
Output: My name is neetu but  what  is this
